### ISSUE TITLE
Define dependencies between Github issues and Buzilla bugs

### ISSUE THREAD

**Issue by pocmo** [mcomella/apt_github_improvements#1]
> As a developer working on an app that depends on bugs in Bugzilla I would like to see those dependencies and the state of them inside the GitHub issue .

**Comment by mcomella** [comment]
@pocmo My v1 looks like this for https://github.com/mozilla-mobile/android-components/issues/158:
![screenshot_2018-07-28 sessionintentprocessor doesn t work when using geckoview issue 158 mozilla-mobile android-compon](https://user-images.githubusercontent.com/759372/43359043-ca2ae332-9250-11e8-8c99-8270b5318c6d.png)

It basically takes all of the BZ links in the document and places them at the top with their summaries/status.

Does this fit your use case? I recognize it doesn't create explicit dependencies: we can change the implementation to only fit dependencies if you like: just give me a definition! If so, how would you like for this to work? e.g. one implementation could be if the comment text includes, "Dependency <bugzilla-url>", it creates a dependency.

**Comment by mcomella** [comment]
By the way, this feature is on master if you wanted to test it out.

**Comment by mcomella** [comment]
I landed the changes on AMO if you want to test them out: https://addons.mozilla.org/en-US/firefox/addon/apt-github-improvements/

This is the same UUID as the Story Points so you'll be upgraded if you have that installed.

**Comment by pocmo** [comment]
That's so awesome, thank you! :)

**Comment by mcomella** [comment]
Sounds like this fits your use case (at least initially)! Please reopen or file a new issue if you want something more from this feature!
