### ISSUE TITLE
Non public bugzilla bugs are displayed as "Bug 0"

### ISSUE THREAD

**Issue by pocmo** [mcomella/apt_github_improvements#13]
Example:
https://github.com/mozilla-mobile/focus-android/issues/1930

This issue contains a link to a legal bug and the text at the top says:

> Bugzilla bugs referenced in this issue:
>  * Bug #0

**Comment by mcomella** [comment]
Thanks for filing!

FYI: this will be in the next release but 1) I may want to finish #10 first before release and 2) I want to test it locally for a few days to make sure I didn't break anything. :)
