### ISSUE TITLE
Links between PRs and issues not appearing

### ISSUE THREAD

**Issue by Baron-Severin** [mcomella/apt_github_improvements#33]
Links from issue to PR, and links from PR to issue are not appearing.  I am reproducing this ~90% of the time.

We found the following error in my logs:
`TypeError: storedIssueToPRs[key] is not iterable`

**Comment by mcomella** [comment]
Looks like this is the section:
https://github.com/mcomella/apt_github_improvements/blob/348cec773df32f90572d2192c7a9be75e0588e22/src/contentScript/github/githubStore.ts#L57-L63

**Comment by mcomella** [comment]
Theories:
- We're storing bad data in the DB
- `for (const key in storedIssueToPRs) {}` is iterating over non-key properties of the returned value; these are not expected but theoretically not impossible
- `storage.get` on a key without a value will return an object with `{key: undefined}`

**Comment by mcomella** [comment]
We're storing a `Set` in the DB: [the docs say](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set#Parameters) it can only store primitives and arrays. Also, we (I think) we previously got burned in #30 for storing non-primitive types in the db that seemed to work in testing so this is the likely culprit.

**Comment by mcomella** [comment]
@Baron-Severin I made a speculative fix as I am unable to reproduce. After upgrading, please let me know if you see the issue again!

**Comment by mcomella** [comment]
This is fixed in v0.5.1.
