### ISSUE TITLE
Story Points: cannot inject content as GitHub DOM has changed

### ISSUE THREAD

**Issue by Sdaswani** [mcomella/apt_github_improvements#40]
HI @mcomella , I saw in the docs the story points feature is only available to APT/Mozilla. Is there any technical reason for this?

"Features for APT/Mozilla specifically (these will generally not appear when the user is not on APT/Mozilla repositories): Story Points"

**Comment by mcomella** [comment]
@Sdaswani Briefly looking at the code, I don't see any technical reasons this should not be available to non-Mozilla users. In fact, I don't think there's any code that prevents this from happening. Have you tried using it on your repository yet? I think it should just work.

> "Features for APT/Mozilla specifically (these will generally not appear when the user is not on APT/Mozilla repositories): Story Points"

I'm guessing I wrote "will **generally** not appear" because it won't appear if you don't have any "size *" labels (iirc) and many non-Mozilla users will not have these labels.

**Comment by Sdaswani** [comment]
@mcomella i did try it and it's not working. Here is my set up:
- FF 67.0.4
- add on prefs: <img width="665" alt="Screen Shot 2019-07-08 at 10 26 17 AM" src="https://user-images.githubusercontent.com/4879954/60829905-e6a9be00-a16a-11e9-9f2f-6238c1611263.png">
- private github repo
- i created these labels <img width="159" alt="Screen Shot 2019-07-08 at 10 27 29 AM" src="https://user-images.githubusercontent.com/4879954/60829976-0f31b800-a16b-11e9-8eb1-e3935ce8c950.png">
- set up a milestone with four issues - 2 S, 1 L, and 1 M

but i'm not seeing the awesome point totals :( .

**Comment by Sdaswani** [comment]
FYI I tried reinstalling the add on but that didn't help. I am going to try and create a public repo and see if that works.

**Comment by Sdaswani** [comment]
doesn't work in my public repo either @mcomella : https://github.com/Sdaswani/testrepo/milestone/1 do you see the story points when you load that milestone. maybe there is some setting in the mozilla-mobile repo that is enabled that other repos need to enable too?

**Comment by mcomella** [comment]
> https://github.com/Sdaswani/testrepo/milestone/1 do you see the story points when you load that milestone?

No, I don't - thanks for hosting the repo so I can debug. I'll take a look.

**Comment by mcomella** [comment]
Story points is also no longer working on my example repo linked from the readme: https://github.com/mcomella/Spoon-Knife/milestone/1

I'm guessing github changed their DOM, which broke the add-on.

**Comment by mcomella** [comment]
This `.issues-listing` node appears to have been removed:
https://github.com/mcomella/apt_github_improvements/blob/8d7707929e3946965ae5c95d86feeb1e89f1f3af/src/contentScript/features/storyPoints.ts#L41

**Comment by mcomella** [comment]
It looks like we can replace:
```js
        let issuesList = document.getElementsByClassName('issues-listing')[0];
        if (issuesList.parentNode) {
            issuesList.parentNode.insertBefore(newNode, issuesList);
        }
```

With something like:
```js
        let issuesList = document.getElementsByClassName('mb-3')[0];
        issuesList.appendChild(newNode);
```

However, I don't have enough time to thoroughly test & deploy at the moment.

**Comment by Sdaswani** [comment]
@mcomella thanks so much for your debugging! I assume folks have stopped used this at Mozilla as you would have noticed the issue earlier? Anyhow, I plan to use it here so that will help drive some Firefox installs. :) Thanks for helping us sprint plan!

I will try to apply your change and test locally. 👍

**Comment by mcomella** [comment]
> I assume folks have stopped used this at Mozilla as you would have noticed the issue earlier?

Yes - my team is still using t-shirt size labels but we moved to GitHub projects and Hilda is pulling it from the API (or by hand, I'm not sure). I'm not sure how other teams handle their sprint planning.

**Comment by Sdaswani** [comment]
Your change works @mcomella ! I will push a PR. Thanks for your help!!!!!

**Comment by Sdaswani** [comment]
@mcomella i'm having trouble pushing a PR:

> ERROR: Permission to mcomella/apt_github_improvements.git denied to Sdaswani.

Can you create the PR or give me rights?

**Comment by Sdaswani** [comment]
FYI I did get it working on both my private repo and the testrepo.

**Comment by mcomella** [comment]
@Sdaswani I pushed the change and published the new version to AMO. Thanks for reporting - let me know if you run into any more issues!

**Comment by mcomella** [comment]
> @mcomella i'm having trouble pushing a PR:
> 
> > ERROR: Permission to mcomella/apt_github_improvements.git denied to Sdaswani.
> 
> Can you create the PR or give me rights?

btw, the typical workflow is for you to create a fork, push to your fork, and open a PR to merge your code from your fork to the upstream repository.

**Comment by Sdaswani** [comment]
Thanks @mcomella for the new fixed version!

Sorry about the miss on forking - I'm so used to being part of a project that I brain farted.
